memory_limit = 512M
upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 300
expose_php = Off
date.timezone = Indian/Mauritius

opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
